name: WPS自动邀请

on:
  workflow_dispatch:
  schedule:
    - cron: "45 0 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "安装依赖包"
        run: pip install -r ./requirements.txt

      - name: "运行 WPS自动邀请"
        run: python3 function/wps_invitation.py
        env:
          WPS_KEY: ${{ secrets.WPS_KEY }}
#最后推送 2021年1月22日
